/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffZlaRouteImport } from './routes/staff.zla'
import { Route as StaffTimesheetsRouteImport } from './routes/staff.timesheets'
import { Route as StaffRotaRouteImport } from './routes/staff.rota'
import { Route as StaffMissingRouteImport } from './routes/staff.missing'
import { Route as StaffHolidaysRouteImport } from './routes/staff.holidays'
import { Route as SafetyMaintenanceRouteImport } from './routes/safety.maintenance'
import { Route as SafetyIncidentsRouteImport } from './routes/safety.incidents'
import { Route as SafetyFirstAidRouteImport } from './routes/safety.first-aid'
import { Route as SafetyDrillsRouteImport } from './routes/safety.drills'
import { Route as HusbandryFeedingScheduleRouteImport } from './routes/husbandry.feeding-schedule'
import { Route as HusbandryDailyRoundsRouteImport } from './routes/husbandry.daily-rounds'
import { Route as HusbandryDailyLogsRouteImport } from './routes/husbandry.daily-logs'
import { Route as ClinicalRecordsRouteImport } from './routes/clinical.records'
import { Route as ClinicalQuarantineRouteImport } from './routes/clinical.quarantine'
import { Route as ClinicalMedicationRouteImport } from './routes/clinical.medication'
import { Route as AnimalsIdRouteImport } from './routes/animals.$id'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminHelpRouteImport } from './routes/admin.help'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffZlaRoute = StaffZlaRouteImport.update({
  id: '/staff/zla',
  path: '/staff/zla',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffTimesheetsRoute = StaffTimesheetsRouteImport.update({
  id: '/staff/timesheets',
  path: '/staff/timesheets',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRotaRoute = StaffRotaRouteImport.update({
  id: '/staff/rota',
  path: '/staff/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMissingRoute = StaffMissingRouteImport.update({
  id: '/staff/missing',
  path: '/staff/missing',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffHolidaysRoute = StaffHolidaysRouteImport.update({
  id: '/staff/holidays',
  path: '/staff/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyMaintenanceRoute = SafetyMaintenanceRouteImport.update({
  id: '/safety/maintenance',
  path: '/safety/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyIncidentsRoute = SafetyIncidentsRouteImport.update({
  id: '/safety/incidents',
  path: '/safety/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyFirstAidRoute = SafetyFirstAidRouteImport.update({
  id: '/safety/first-aid',
  path: '/safety/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyDrillsRoute = SafetyDrillsRouteImport.update({
  id: '/safety/drills',
  path: '/safety/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryFeedingScheduleRoute =
  HusbandryFeedingScheduleRouteImport.update({
    id: '/husbandry/feeding-schedule',
    path: '/husbandry/feeding-schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const HusbandryDailyRoundsRoute = HusbandryDailyRoundsRouteImport.update({
  id: '/husbandry/daily-rounds',
  path: '/husbandry/daily-rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryDailyLogsRoute = HusbandryDailyLogsRouteImport.update({
  id: '/husbandry/daily-logs',
  path: '/husbandry/daily-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRecordsRoute = ClinicalRecordsRouteImport.update({
  id: '/clinical/records',
  path: '/clinical/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalQuarantineRoute = ClinicalQuarantineRouteImport.update({
  id: '/clinical/quarantine',
  path: '/clinical/quarantine',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalMedicationRoute = ClinicalMedicationRouteImport.update({
  id: '/clinical/medication',
  path: '/clinical/medication',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIdRoute = AnimalsIdRouteImport.update({
  id: '/animals/$id',
  path: '/animals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/admin/help',
  path: '/admin/help',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/clinical/medication': typeof ClinicalMedicationRoute
  '/clinical/quarantine': typeof ClinicalQuarantineRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/daily-rounds': typeof HusbandryDailyRoundsRoute
  '/husbandry/feeding-schedule': typeof HusbandryFeedingScheduleRoute
  '/safety/drills': typeof SafetyDrillsRoute
  '/safety/first-aid': typeof SafetyFirstAidRoute
  '/safety/incidents': typeof SafetyIncidentsRoute
  '/safety/maintenance': typeof SafetyMaintenanceRoute
  '/staff/holidays': typeof StaffHolidaysRoute
  '/staff/missing': typeof StaffMissingRoute
  '/staff/rota': typeof StaffRotaRoute
  '/staff/timesheets': typeof StaffTimesheetsRoute
  '/staff/zla': typeof StaffZlaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/clinical/medication': typeof ClinicalMedicationRoute
  '/clinical/quarantine': typeof ClinicalQuarantineRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/daily-rounds': typeof HusbandryDailyRoundsRoute
  '/husbandry/feeding-schedule': typeof HusbandryFeedingScheduleRoute
  '/safety/drills': typeof SafetyDrillsRoute
  '/safety/first-aid': typeof SafetyFirstAidRoute
  '/safety/incidents': typeof SafetyIncidentsRoute
  '/safety/maintenance': typeof SafetyMaintenanceRoute
  '/staff/holidays': typeof StaffHolidaysRoute
  '/staff/missing': typeof StaffMissingRoute
  '/staff/rota': typeof StaffRotaRoute
  '/staff/timesheets': typeof StaffTimesheetsRoute
  '/staff/zla': typeof StaffZlaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/clinical/medication': typeof ClinicalMedicationRoute
  '/clinical/quarantine': typeof ClinicalQuarantineRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/daily-rounds': typeof HusbandryDailyRoundsRoute
  '/husbandry/feeding-schedule': typeof HusbandryFeedingScheduleRoute
  '/safety/drills': typeof SafetyDrillsRoute
  '/safety/first-aid': typeof SafetyFirstAidRoute
  '/safety/incidents': typeof SafetyIncidentsRoute
  '/safety/maintenance': typeof SafetyMaintenanceRoute
  '/staff/holidays': typeof StaffHolidaysRoute
  '/staff/missing': typeof StaffMissingRoute
  '/staff/rota': typeof StaffRotaRoute
  '/staff/timesheets': typeof StaffTimesheetsRoute
  '/staff/zla': typeof StaffZlaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/help'
    | '/admin/reports'
    | '/admin/settings'
    | '/animals/$id'
    | '/clinical/medication'
    | '/clinical/quarantine'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/daily-rounds'
    | '/husbandry/feeding-schedule'
    | '/safety/drills'
    | '/safety/first-aid'
    | '/safety/incidents'
    | '/safety/maintenance'
    | '/staff/holidays'
    | '/staff/missing'
    | '/staff/rota'
    | '/staff/timesheets'
    | '/staff/zla'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/help'
    | '/admin/reports'
    | '/admin/settings'
    | '/animals/$id'
    | '/clinical/medication'
    | '/clinical/quarantine'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/daily-rounds'
    | '/husbandry/feeding-schedule'
    | '/safety/drills'
    | '/safety/first-aid'
    | '/safety/incidents'
    | '/safety/maintenance'
    | '/staff/holidays'
    | '/staff/missing'
    | '/staff/rota'
    | '/staff/timesheets'
    | '/staff/zla'
  id:
    | '__root__'
    | '/'
    | '/admin/help'
    | '/admin/reports'
    | '/admin/settings'
    | '/animals/$id'
    | '/clinical/medication'
    | '/clinical/quarantine'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/daily-rounds'
    | '/husbandry/feeding-schedule'
    | '/safety/drills'
    | '/safety/first-aid'
    | '/safety/incidents'
    | '/safety/maintenance'
    | '/staff/holidays'
    | '/staff/missing'
    | '/staff/rota'
    | '/staff/timesheets'
    | '/staff/zla'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AnimalsIdRoute: typeof AnimalsIdRoute
  ClinicalMedicationRoute: typeof ClinicalMedicationRoute
  ClinicalQuarantineRoute: typeof ClinicalQuarantineRoute
  ClinicalRecordsRoute: typeof ClinicalRecordsRoute
  HusbandryDailyLogsRoute: typeof HusbandryDailyLogsRoute
  HusbandryDailyRoundsRoute: typeof HusbandryDailyRoundsRoute
  HusbandryFeedingScheduleRoute: typeof HusbandryFeedingScheduleRoute
  SafetyDrillsRoute: typeof SafetyDrillsRoute
  SafetyFirstAidRoute: typeof SafetyFirstAidRoute
  SafetyIncidentsRoute: typeof SafetyIncidentsRoute
  SafetyMaintenanceRoute: typeof SafetyMaintenanceRoute
  StaffHolidaysRoute: typeof StaffHolidaysRoute
  StaffMissingRoute: typeof StaffMissingRoute
  StaffRotaRoute: typeof StaffRotaRoute
  StaffTimesheetsRoute: typeof StaffTimesheetsRoute
  StaffZlaRoute: typeof StaffZlaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/zla': {
      id: '/staff/zla'
      path: '/staff/zla'
      fullPath: '/staff/zla'
      preLoaderRoute: typeof StaffZlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/timesheets': {
      id: '/staff/timesheets'
      path: '/staff/timesheets'
      fullPath: '/staff/timesheets'
      preLoaderRoute: typeof StaffTimesheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/rota': {
      id: '/staff/rota'
      path: '/staff/rota'
      fullPath: '/staff/rota'
      preLoaderRoute: typeof StaffRotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/missing': {
      id: '/staff/missing'
      path: '/staff/missing'
      fullPath: '/staff/missing'
      preLoaderRoute: typeof StaffMissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/holidays': {
      id: '/staff/holidays'
      path: '/staff/holidays'
      fullPath: '/staff/holidays'
      preLoaderRoute: typeof StaffHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/maintenance': {
      id: '/safety/maintenance'
      path: '/safety/maintenance'
      fullPath: '/safety/maintenance'
      preLoaderRoute: typeof SafetyMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/incidents': {
      id: '/safety/incidents'
      path: '/safety/incidents'
      fullPath: '/safety/incidents'
      preLoaderRoute: typeof SafetyIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/first-aid': {
      id: '/safety/first-aid'
      path: '/safety/first-aid'
      fullPath: '/safety/first-aid'
      preLoaderRoute: typeof SafetyFirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/drills': {
      id: '/safety/drills'
      path: '/safety/drills'
      fullPath: '/safety/drills'
      preLoaderRoute: typeof SafetyDrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/feeding-schedule': {
      id: '/husbandry/feeding-schedule'
      path: '/husbandry/feeding-schedule'
      fullPath: '/husbandry/feeding-schedule'
      preLoaderRoute: typeof HusbandryFeedingScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/daily-rounds': {
      id: '/husbandry/daily-rounds'
      path: '/husbandry/daily-rounds'
      fullPath: '/husbandry/daily-rounds'
      preLoaderRoute: typeof HusbandryDailyRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/daily-logs': {
      id: '/husbandry/daily-logs'
      path: '/husbandry/daily-logs'
      fullPath: '/husbandry/daily-logs'
      preLoaderRoute: typeof HusbandryDailyLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/records': {
      id: '/clinical/records'
      path: '/clinical/records'
      fullPath: '/clinical/records'
      preLoaderRoute: typeof ClinicalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/quarantine': {
      id: '/clinical/quarantine'
      path: '/clinical/quarantine'
      fullPath: '/clinical/quarantine'
      preLoaderRoute: typeof ClinicalQuarantineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/medication': {
      id: '/clinical/medication'
      path: '/clinical/medication'
      fullPath: '/clinical/medication'
      preLoaderRoute: typeof ClinicalMedicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$id': {
      id: '/animals/$id'
      path: '/animals/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AnimalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/admin/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AnimalsIdRoute: AnimalsIdRoute,
  ClinicalMedicationRoute: ClinicalMedicationRoute,
  ClinicalQuarantineRoute: ClinicalQuarantineRoute,
  ClinicalRecordsRoute: ClinicalRecordsRoute,
  HusbandryDailyLogsRoute: HusbandryDailyLogsRoute,
  HusbandryDailyRoundsRoute: HusbandryDailyRoundsRoute,
  HusbandryFeedingScheduleRoute: HusbandryFeedingScheduleRoute,
  SafetyDrillsRoute: SafetyDrillsRoute,
  SafetyFirstAidRoute: SafetyFirstAidRoute,
  SafetyIncidentsRoute: SafetyIncidentsRoute,
  SafetyMaintenanceRoute: SafetyMaintenanceRoute,
  StaffHolidaysRoute: StaffHolidaysRoute,
  StaffMissingRoute: StaffMissingRoute,
  StaffRotaRoute: StaffRotaRoute,
  StaffTimesheetsRoute: StaffTimesheetsRoute,
  StaffZlaRoute: StaffZlaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
